export const fakeVideos = [
  {
    id: 1,
    title: "videoDEPOIMENTO01",
    duration: "01:12",
    rate: 1,
    youtubeId: "wR15AkpsgCE",
    coHost: "outrohost1",
    guests: "convidado1",
  },
  {
    id: 2,
    title: "videoDEPOIMENTO02",
    duration: "02:56",
    rate: 2,
    youtubeId: "wR15AkpsgCE",
    coHost: "outrohost2",
    guests: "convidado2",
  },
  {
    id: 3,
    title: "videoDEPOIMENTO03",
    duration: "01:44",
    rate: 3,
    youtubeId: "wR15AkpsgCE",
    coHost: "",
    guests: "convidado3",
  },
  {
    id: 4,
    title: "videoDEPOIMENTO04",
    duration: "03:28",
    rate: 4,
    youtubeId: "wR15AkpsgCE",
    coHost: "outrohost4",
    guests: "convidado4",
  },
];
